### ISSUE TITLE
Problem with ban

### ISSUE THREAD

**Issue by linkinkov** [r0306/Anti-Relog#2]
In start server, plugin work, but if in pvp player leave, plugin dont ban and player dont lose items. In console have error.

[SEVERE] Could not pass event PlayerQuitEvent to AntiRelog org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332) at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477) at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462) at net.minecraft.server.ServerConfigurationManagerAbstract.disconnect(ServerConfigurationManagerAbstract.java:213) at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:711) at net.minecraft.server.NetworkManager.b(NetworkManager.java:281) at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109) at net.minecraft.server.ServerConnection.b(SourceFile:35) at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30) at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:582) at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213) at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:475) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407) at net.minecraft.server.ThreadServerApplication.run(SourceFile:539) Caused by: java.lang.NullPointerException at com.github.r0306.AntiRelog.Listeners.LogPrevention.isPvPLog(LogPrevention.java:244) at com.github.r0306.AntiRelog.Listeners.LogPrevention.onQuit(LogPrevention.java:47) at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:601) at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330) ... 14 more

I use last bild Spigot 1.3.1

**Comment by r0306** [comment]
The issue has been addressed with the 1.5.1 update.
